language: python
python:
- '2.6'
- '2.7'
install: pip install -r requirements.txt
script: python flaskr_tests.py
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: bucbx6+7zJoSbg9QEgj/efJLcLzdEn+s15JSNjMCpvYFRhKFiskmZA7QwTH5Cd2452xJGC+6i0ZCso0z57+IiCJ7VTSD0kmx2SQlAEDsDo+nvZGr/ZXkEipBNF+oZ0rVo6zYx7aRjQ07h6TQWxyWQeQrCYMp+29l+nrk7IzHsPLAXLFhk0zgrIp2cioIJzyeDq+nHcOciqkfiv1Rr1ojXE6etM340Fl10EWQQwlDg9lzuKFfFeHM4vS2hjkbC/zpvwfYu0rf1HRQs9Dm8INvc5VaBflDn59fEnRIwTcK8CYVGWoW3bUYq1v4NaUSFhfhWyfYOV+OEBM2sabXEiuIMgv84YsXZZdExDTBypKv2jhL/sIjawHoZgE228Bvo9GXa1z+VDH5+UrX7N5+jSh8U4dCF2kn4OmFJW9rn9JB1epdW8hDFSeCm3AaQ1GMFxWGNx6C8IY4jeEZhStZda+S39+dQ4Lufd4Aa0tGwkZysG8sM+B0zFdM3bvX7UILp9DxVM8PZB5N/YTddwH1oEJdtQJZYdOyz6x6Kd/ST0kAdmUv8QB58yrikW9CNtkdL2EsbY0N/pxTh+PxuL13F8FvspRrgyHEdDntRNzJpJwT//WoQo4wXV4kDJzvreIm29YUagpabwgrA00uC6HxzObg11KnYEcFvCcJ+x0XkM6hhoY=
  app: dazhelp
