language: python
python:
- '2.6'
- '2.7'
install: pip install -r requirements.txt
script: python flaskr_tests.py
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: asdh12P2Z8PLVucl7GSXFx8UQmoqQWMDiBW6SYsdApnI5f2CgbU3cUK8Ir3w/tu9poQtjfEDYNGoQDgUIjDc/+kVKxDbNZCGe9kEiHAxIX7DBCi+ggcec5NSfiQC4X/17eg1jOPkUxj5jkuRHRRU785gwgUtNmsLWi65JvBXZyRZT0D5ZlzZLzbsF0sNQ8xcY/qCNzJFCBxn2W2pAuFdvozvOBqo3JvlbkYxVJhDfsEFO9CIkFnCzDMzl4+OHFxVskPo5+50HCJsHccWQ6Xy9XhseQCp520606QJcfW/6MGqRb167/v8zN3s5MjlE71ZWsSzWmqv2RHJRgllshtD0k6IYUnJ6BZBpcm2Z6LLGswSJRhDHEGXtbT37yNplP5FnYnVVmVM6fAVVEbQEAHpal3vg13yQPTzg+plXacb9ib+WGEo+lHiX8r1jQPgHyjvo3UuImY46bXKfDvsRAbwx/V37nINLINW+fmwnm2IaGDO5ZnyknIQ0TBQUyV4gpqvHsLsHXAD0qDYqccuMX88VrT+sJ/oy4rh8m8k/0gSLWkcATG1CS2m8hQaXeJgc0KvBz7crboB+hlqX9+ySLAoKvmF8HuUZBvR3hiwHYZ3PGs3WSyAHwk9PY9k8kdNh1xXC4s0m60+lnD2ttQwoNpsBR01y1+USfhhPib0rGSM3/A=
  app: dazhelp
